### ISSUE TITLE
PlotBasinSummary bug

### ISSUE THREAD

**Issue by a753bart** [rcapell/HYPEtools#55] opened 2016-10-05 07:29 UTC
The log version of the plot is working strangely for some subids. I suspect it happens when there are some zeros in the series (in my case it was simulated flows). Instead of plotting the non-zero values only, there is an empty chart. 
![plot_9001154_bassum](https://cloud.githubusercontent.com/assets/20319028/19104641/15aa6278-8ade-11e6-8909-ca559ee579b4.png)
![plot_9001154_bassum_log](https://cloud.githubusercontent.com/assets/20319028/19104643/179c5456-8ade-11e6-904f-a3115432f8f2.png)

**Comment by rcapell** [comment] 2016-10-05 09:10
not good.
Can you email or upload the basin output file for testing? -thanks

**Comment by a753bart** [comment] 2016-10-05 09:19
Here is the output.
[9001154.txt](https://github.com/rcapell/HYPEtools/files/510536/9001154.txt)

**Comment by rcapell** [comment] 2016-10-05 11:25
Works now, was caused by axis limits definition, which could result in negative minima even with log-scaled axes. I put in an exception handling for that. 
Also updated PlotSimObsRegime(), so that y-axis limits work better with log-scaling (see TP in your plot example, huge space att bottom of plot, this works better now).
Closing.

**Closed by rcapell** 2016-10-05 11:25 UTC
Labels: bug
