### ISSUE TITLE
Error detected in ReadObs function

### ISSUE THREAD

**Issue by josevalles7** [rcapell/HYPEtools#125] opened 2021-09-11 18:04 UTC
Hello

I've been trying to use the ReadObs function but I always obtain the following error: 

Error in UseMethod("reclass_date", orig) : 
  no applicable method for 'reclass_date' applied to an object of class "character"

In addition, it shows warning message 

Column 'DATE' was requested to be 'POSIXct' but fread encountered the following error:
	character string is not in a standard unambiguous format
so the column has been left as type 'character' 

Do you know what the situation could be? 

Regards

**Comment by rcapell** [comment] 2021-09-13 08:03
Hi Jose,
thanks for your report! Could you paste/attach an example of the file you get the error with, plus you ReadObs call?
Thanks, René

**Comment by josevalles7** [comment] 2021-09-13 19:18
Hi René 

I have attended the HYPE Course and I was unable to read the Qobs.txt file from the course. 

[Qobs.txt](https://github.com/rcapell/HYPEtools/files/7156843/Qobs.txt)

The error that I got is the following

![image](https://user-images.githubusercontent.com/34262265/133143380-34e11655-e360-41d2-ab78-8aeb5d5c4fc6.png)

**Comment by rcapell** [comment] 2021-09-13 19:48
Ah, Jose, I didn't make the course connection, good to hear that you ar hype-ing away, even after the course :smile:!

I think we had one other participant with a similar problem during the course. 
For me, the import works without problems:
```R
> library(HYPEtools)
HYPEtools version 0.5.1. Find the latest release at: https://github.com/rcapell/HYPEtools/releases
Please report bugs and feature requests at: https://github.com/rcapell/HYPEtools/issues
> te <- ReadObs("../issues/125/Qobs.txt")
> head(te)
        DATE 314495
1 1961-01-01   12.6
2 1961-01-02   12.6
3 1961-01-03   12.3
4 1961-01-04   12.3
5 1961-01-05   12.3
6 1961-01-06   12.3
> 
```
I wonder if this could be related to localisation, i.e. your region/language-specific system settings. It is just a guess, though.
Can you try to pass the date format string explicitly, i.e. sth. like:
```R
> te <- ReadObs("../issues/125/Qobs.txt", dt.format = "%Y-%m-%d")
```
If that does not work, can you test an fread import? ReadObs is essentially a wrapper for fread (below the function calls and results I get from them):
```R
> # standard fread
> te <- fread("../issues/125/Qobs.txt")
> str(te)
Classes ‘data.table’ and 'data.frame':	20454 obs. of  2 variables:
 $ DATE  : IDate, format: "1961-01-01" "1961-01-02" "1961-01-03" "1961-01-04" ...
 $ 314495: num  12.6 12.6 12.3 12.3 12.3 12.3 12 12 12 12.3 ...
 - attr(*, ".internal.selfref")=<externalptr> 
> # forced POSIXct dates, as used in ReadObs
> te <- fread("../issues/125/Qobs.txt", colClasses = list("POSIXct" = 1))
> str(te)
Classes ‘data.table’ and 'data.frame':	20454 obs. of  2 variables:
 $ DATE  : POSIXct, format: "1961-01-01" "1961-01-02" "1961-01-03" "1961-01-04" ...
 $ 314495: num  12.6 12.6 12.3 12.3 12.3 12.3 12 12 12 12.3 ...
 - attr(*, ".internal.selfref")=<externalptr> 
> 
```

And, just for the sake of completeness: I assume you run with the HYPEtools 0.5.1, correct?

**Comment by josevalles7** [comment] 2021-09-14 00:41
Hi. Yes I am re-doing the course before implementing the HYPE model in my basins. I had the same issue during the course but I didn't send the question. I really don't know why

I passed the date format but same result 

> qobs <- ReadObs(paste0(hypepth, "Qobs.txt"),dt.format = "%Y-%m-%d")

```
Error in UseMethod("reclass_date", orig) : 
  no applicable method for 'reclass_date' applied to an object of class "character"
In addition: Warning message:
Column 'DATE' was requested to be 'POSIXct' but fread encountered the following error:
	character string is not in a standard unambiguous format
so the column has been left as type 'character' 
```

I have tested fread function and it works well 

> te <- fread(paste0(hypepth, "Qobs.txt"))
> str(te)

```
Classes ‘data.table’ and 'data.frame':	22033 obs. of  2 variables:
 $ DATE: IDate, format: "1961-01-01" "1961-01-02" "1961-01-03" "1961-01-04" ...
 $ 3587: num  -9999 -9999 -9999 -9999 -9999 ...
 - attr(*, ".internal.selfref")=<externalptr> 
```


And yes... I'm using the HYPEtools 0.5.1

**Comment by rcapell** [comment] 2021-09-14 09:01
Hm. I think we'll have to iterate a bit on this one, hope that works for you!
I am still thinking this might be locale-related, can you try and run these commands for me and paste the results here?
First, a forced Posix-formatting with fread:
```R
# forced POSIXct dates, as used in ReadObs
te <- fread("../issues/125/Qobs.txt", colClasses = list("POSIXct" = 1))
str(te)
```
And second your locale settings, in the hope that I can emulate them on my machine for testing:
```R
> Sys.getlocale()
```

**Comment by josevalles7** [comment] 2021-09-14 19:26
Don't worry. It's ok for me 

Here are the results
> te <- fread(paste0(hypepth, "Qobs.txt"), colClasses = list("POSIXct" = 1))

`
Warning message:
Column 'DATE' was requested to be 'POSIXct' but fread encountered the following error:
	character string is not in a standard unambiguous format
so the column has been left as type 'character' 
`

the local settings 

> Sys.getlocale()

`[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"`

Let me know if you need more info

**Comment by rcapell** [comment] 2021-09-14 20:14
Hmhm, I changed the locale to different US flavours (not exactly yours, but they seem to be platform-dependent), but I am still not able to reproduce the error. Can you test the attached function? I shuffled a few things around with POSIX conversion, maybe this does the trick.
Unzip the attached file, source the function and then run ReadObs:
```R
source("function_ReadObs.R")
qobs <- ReadObs(paste0(hypepth, "Qobs.txt"))
```
Also, what version of data.table do you use (another stab in the dark)? I use 1.14.0.


[function_ReadObs.zip](https://github.com/rcapell/HYPEtools/files/7164826/function_ReadObs.zip)

**Comment by josevalles7** [comment] 2021-09-15 14:42
Hi René

The function works!! I was able to import the observe data. 

> source("function_ReadObs.R")
> qobs <- ReadObs(paste0(hypepth, "Qobs.txt"))
> tail(qobs)

```
            DATE  3587
22028 2021-04-23 2.835
22029 2021-04-24 2.818
22030 2021-04-25 2.796
22031 2021-04-26 2.775
22032 2021-04-27 2.757
22033 2021-04-28 2.734
```

The data.table version that I'm using is the 1.14.0

**Comment by rcapell** [comment] 2021-09-15 14:47
Ok, great, then I will try and incorporate this into the packaged function. Will close this ticket when it is done. In the meantime you'll have to make do with the replacement function :smile:

**Comment by josevalles7** [comment] 2021-09-15 23:53
Of course

Thank you for attending the issue :D

**Comment by josevalles7** [comment] 2021-11-23 17:22
Hi René, I hope everything is ok 

I've been using the ReadObs function that  you have provided me before. 

I also have implement the HYPE conceptual framework in a local basin in Uruguay. However, when I use the ReadObs function, it provide an error 

`
hypepth <- "d:/Documentos/documents dinagua/2021/Laguna Negra/HYPE Model/"

qobs <- ReadObs(paste0(hypepth, "__Qobs.txt"),dt.format = "%Y-%m-%d")

Error in if (!is.na(tdff)) { : argument is of length zero
`


Also, I have some water level observation that I was not able to import correctly using ReadXobs function. I mean, the function runs perfectly but the resulting variable is as follow

`
wobs <- ReadXobs(paste0(hypepth, "wobs.txt"),dt.format = "%Y-%m-%d")

head(wobs)
        date -9999_-9999

1 1999-01-03          NA

2 1999-01-04          NA

3 1999-01-05          NA

4 1999-01-06          NA

5 1999-01-07          NA

6 1999-01-08          NA
`


As you can see, the column name in the water level column is labeled -9999_-9999 and is not importing the first two rows in the file

Let me know your thoughts 

Regards

**Comment by josevalles7** [comment] 2021-11-23 17:26
Here are the files in case you want to test it 

[Qobs.txt](https://github.com/rcapell/HYPEtools/files/7589962/Qobs.txt)
[Wobs.txt](https://github.com/rcapell/HYPEtools/files/7589963/Wobs.txt)

**Comment by c-brendel** [comment] 2021-11-24 09:19
Hi Jose!

The problem with your Qobs file was that your date column was called "date" instead of "DATE". I've fixed this bug in the ReadObs() function so it doesn't matter if the column is capitalized or not. To get the new version of the function, you will have to install the latest develop version of HYPEtools, but if that's difficult to do, then it's probably just easier to change the name of your column.

For the Wobs.txt file, HYPE has a slightly different format for Xobs.txt files than for the Qobs.txt files. For Xobs.txt files, the first row needs to be the variable name, the second row is the subbasin ID, and observations start on the third row. Here's some more information about the correct format: http://www.smhi.net/hype/wiki/doku.php?id=start:hype_file_reference:xobs.txt

Conrad

**Comment by josevalles7** [comment] 2021-11-24 13:00
> Ok, great, then I will try and incorporate this into the packaged function. Will close this ticket when it is done. In the meantime you'll have to make do with the replacement function 😄

Hi Conrad 

Thank you for the support. I have seen that you have updated the function in order to fix the "DATE" vs "date" issue. However, I was wondering if the updated function also includes the previous case (error in ReadObs relate to the  
`
"Error in UseMethod("reclass_date", orig) : no applicable method for 'reclass_date' applied to an object of class "character" 
`
Previosly, René sent me the source function that was working correctly 

Jose Valles

**Comment by c-brendel** [comment] 2021-11-24 13:13
Hi Jose,
I was able to read the Qobs.txt and Wobs.txt files using the functions in the packaged version, so I think it should have the update from René. I will double check with him though!

Conrad

**Comment by rcapell** [comment] 2021-11-24 13:20
I don't think I pushed it yet, will do so within a few hours!


________________________________
Från: c-brendel ***@***.***>
Skickat: den 24 november 2021 14:13
Till: rcapell/HYPEtools
Kopia: Capell René; Comment
Ämne: Re: [rcapell/HYPEtools] Error detected in ReadObs function (#125)


Hi Jose,
I was able to read the Qobs.txt and Wobs.txt files using the functions in the packaged version, so I think it should have the update from René. I will double check with him though!

Conrad

**Closed** 2021-11-26 08:32 UTC
Labels: bug

**Comment by rcapell** [comment] 2021-11-26 08:35
@josevalles7 Date conversion fix added.

**Comment by josevalles7** [comment] 2021-11-26 14:06
> @josevalles7 Date conversion fix added.

Thanks! the latest version works for me

Regards
